apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-oppgave-listener
    team: teamdigihot
  name: hm-oppgave-listener
  namespace: teamdigihot
spec:
  image: "{{image}}"
  strategy:
    type: Recreate
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  valkey:
    - instance: broker
      access: readwrite
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: hotsak-frontend
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  env:
    - name: HTTP_PORT
      value: "8080"
    - name: KAFKA_APPLICATION_ID
      value: "hm-oppgave-listener-v1"
    - name: KAFKA_RAPID_TOPIC
      value: "teamdigihot.hm-soknadsbehandling-v1"
    - name: OPPGAVE_TOPIC
      value: "oppgavehandtering.oppgavehendelse-v1"
    - name: OPPGAVE_LISTENER_LOG_LEVEL
      value: DEBUG
